<template>
  <div class="container flex">
    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae, eum
    repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae,
    eum repudiandae cum voluptates vitae assumenda temporibus itaque totam autem
    inventore maiores atque amet, dolor doloremque ea vero incidunt blanditiis
    non.
  </div>
</template>

<script setup>
const userStore = useUserStore();

const profile = computed(() => {
  return userStore._state.user;
});
</script>
