
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BaseAlert': typeof import("../components/base/Alert.vue")['default']
    'BaseAvatar': typeof import("../components/base/Avatar.vue")['default']
    'BaseBreadCrumbs': typeof import("../components/base/BreadCrumbs.vue")['default']
    'BaseButton': typeof import("../components/base/Button.vue")['default']
    'BaseCard': typeof import("../components/base/Card.vue")['default']
    'BaseChip': typeof import("../components/base/Chip.vue")['default']
    'BaseConfrim': typeof import("../components/base/Confrim.vue")['default']
    'BaseDivider': typeof import("../components/base/Divider.vue")['default']
    'BaseDrawer': typeof import("../components/base/Drawer.vue")['default']
    'BaseEmptyState': typeof import("../components/base/EmptyState.vue")['default']
    'BaseIcon': typeof import("../components/base/Icon.vue")['default']
    'BaseIconContent': typeof import("../components/base/IconContent.vue")['default']
    'BaseInput': typeof import("../components/base/Input.vue")['default']
    'BaseModal': typeof import("../components/base/Modal.vue")['default']
    'BaseModuleState': typeof import("../components/base/ModuleState.vue")['default']
    'BaseOtp': typeof import("../components/base/Otp.vue")['default']
    'BaseSelect': typeof import("../components/base/Select.vue")['default']
    'BaseSkeleton': typeof import("../components/base/Skeleton.vue")['default']
    'BaseTab': typeof import("../components/base/Tab.vue")['default']
    'BaseTextarea': typeof import("../components/base/Textarea.vue")['default']
    'BaseToast': typeof import("../components/base/Toast.vue")['default']
    'BaseToastBar': typeof import("../components/base/ToastBar.vue")['default']
    'BaseUploadAvatar': typeof import("../components/base/UploadAvatar.vue")['default']
    'BaseUploadImage': typeof import("../components/base/UploadImage.vue")['default']
    'Compose': typeof import("../components/compose/index.vue")['default']
    'LayoutsAdminHeader': typeof import("../components/layouts/admin/Header.vue")['default']
    'LayoutsAdminSidebar': typeof import("../components/layouts/admin/Sidebar.vue")['default']
    'LayoutsAdmin': typeof import("../components/layouts/admin/index.vue")['default']
    'LayoutsShopHeader': typeof import("../components/layouts/shop/Header.vue")['default']
    'LayoutsShopSidebar': typeof import("../components/layouts/shop/Sidebar.vue")['default']
    'LayoutsShop': typeof import("../components/layouts/shop/index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBaseAlert': typeof import("../components/base/Alert.vue")['default']
    'LazyBaseAvatar': typeof import("../components/base/Avatar.vue")['default']
    'LazyBaseBreadCrumbs': typeof import("../components/base/BreadCrumbs.vue")['default']
    'LazyBaseButton': typeof import("../components/base/Button.vue")['default']
    'LazyBaseCard': typeof import("../components/base/Card.vue")['default']
    'LazyBaseChip': typeof import("../components/base/Chip.vue")['default']
    'LazyBaseConfrim': typeof import("../components/base/Confrim.vue")['default']
    'LazyBaseDivider': typeof import("../components/base/Divider.vue")['default']
    'LazyBaseDrawer': typeof import("../components/base/Drawer.vue")['default']
    'LazyBaseEmptyState': typeof import("../components/base/EmptyState.vue")['default']
    'LazyBaseIcon': typeof import("../components/base/Icon.vue")['default']
    'LazyBaseIconContent': typeof import("../components/base/IconContent.vue")['default']
    'LazyBaseInput': typeof import("../components/base/Input.vue")['default']
    'LazyBaseModal': typeof import("../components/base/Modal.vue")['default']
    'LazyBaseModuleState': typeof import("../components/base/ModuleState.vue")['default']
    'LazyBaseOtp': typeof import("../components/base/Otp.vue")['default']
    'LazyBaseSelect': typeof import("../components/base/Select.vue")['default']
    'LazyBaseSkeleton': typeof import("../components/base/Skeleton.vue")['default']
    'LazyBaseTab': typeof import("../components/base/Tab.vue")['default']
    'LazyBaseTextarea': typeof import("../components/base/Textarea.vue")['default']
    'LazyBaseToast': typeof import("../components/base/Toast.vue")['default']
    'LazyBaseToastBar': typeof import("../components/base/ToastBar.vue")['default']
    'LazyBaseUploadAvatar': typeof import("../components/base/UploadAvatar.vue")['default']
    'LazyBaseUploadImage': typeof import("../components/base/UploadImage.vue")['default']
    'LazyCompose': typeof import("../components/compose/index.vue")['default']
    'LazyLayoutsAdminHeader': typeof import("../components/layouts/admin/Header.vue")['default']
    'LazyLayoutsAdminSidebar': typeof import("../components/layouts/admin/Sidebar.vue")['default']
    'LazyLayoutsAdmin': typeof import("../components/layouts/admin/index.vue")['default']
    'LazyLayoutsShopHeader': typeof import("../components/layouts/shop/Header.vue")['default']
    'LazyLayoutsShopSidebar': typeof import("../components/layouts/shop/Sidebar.vue")['default']
    'LazyLayoutsShop': typeof import("../components/layouts/shop/index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BaseAlert: typeof import("../components/base/Alert.vue")['default']
export const BaseAvatar: typeof import("../components/base/Avatar.vue")['default']
export const BaseBreadCrumbs: typeof import("../components/base/BreadCrumbs.vue")['default']
export const BaseButton: typeof import("../components/base/Button.vue")['default']
export const BaseCard: typeof import("../components/base/Card.vue")['default']
export const BaseChip: typeof import("../components/base/Chip.vue")['default']
export const BaseConfrim: typeof import("../components/base/Confrim.vue")['default']
export const BaseDivider: typeof import("../components/base/Divider.vue")['default']
export const BaseDrawer: typeof import("../components/base/Drawer.vue")['default']
export const BaseEmptyState: typeof import("../components/base/EmptyState.vue")['default']
export const BaseIcon: typeof import("../components/base/Icon.vue")['default']
export const BaseIconContent: typeof import("../components/base/IconContent.vue")['default']
export const BaseInput: typeof import("../components/base/Input.vue")['default']
export const BaseModal: typeof import("../components/base/Modal.vue")['default']
export const BaseModuleState: typeof import("../components/base/ModuleState.vue")['default']
export const BaseOtp: typeof import("../components/base/Otp.vue")['default']
export const BaseSelect: typeof import("../components/base/Select.vue")['default']
export const BaseSkeleton: typeof import("../components/base/Skeleton.vue")['default']
export const BaseTab: typeof import("../components/base/Tab.vue")['default']
export const BaseTextarea: typeof import("../components/base/Textarea.vue")['default']
export const BaseToast: typeof import("../components/base/Toast.vue")['default']
export const BaseToastBar: typeof import("../components/base/ToastBar.vue")['default']
export const BaseUploadAvatar: typeof import("../components/base/UploadAvatar.vue")['default']
export const BaseUploadImage: typeof import("../components/base/UploadImage.vue")['default']
export const Compose: typeof import("../components/compose/index.vue")['default']
export const LayoutsAdminHeader: typeof import("../components/layouts/admin/Header.vue")['default']
export const LayoutsAdminSidebar: typeof import("../components/layouts/admin/Sidebar.vue")['default']
export const LayoutsAdmin: typeof import("../components/layouts/admin/index.vue")['default']
export const LayoutsShopHeader: typeof import("../components/layouts/shop/Header.vue")['default']
export const LayoutsShopSidebar: typeof import("../components/layouts/shop/Sidebar.vue")['default']
export const LayoutsShop: typeof import("../components/layouts/shop/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBaseAlert: typeof import("../components/base/Alert.vue")['default']
export const LazyBaseAvatar: typeof import("../components/base/Avatar.vue")['default']
export const LazyBaseBreadCrumbs: typeof import("../components/base/BreadCrumbs.vue")['default']
export const LazyBaseButton: typeof import("../components/base/Button.vue")['default']
export const LazyBaseCard: typeof import("../components/base/Card.vue")['default']
export const LazyBaseChip: typeof import("../components/base/Chip.vue")['default']
export const LazyBaseConfrim: typeof import("../components/base/Confrim.vue")['default']
export const LazyBaseDivider: typeof import("../components/base/Divider.vue")['default']
export const LazyBaseDrawer: typeof import("../components/base/Drawer.vue")['default']
export const LazyBaseEmptyState: typeof import("../components/base/EmptyState.vue")['default']
export const LazyBaseIcon: typeof import("../components/base/Icon.vue")['default']
export const LazyBaseIconContent: typeof import("../components/base/IconContent.vue")['default']
export const LazyBaseInput: typeof import("../components/base/Input.vue")['default']
export const LazyBaseModal: typeof import("../components/base/Modal.vue")['default']
export const LazyBaseModuleState: typeof import("../components/base/ModuleState.vue")['default']
export const LazyBaseOtp: typeof import("../components/base/Otp.vue")['default']
export const LazyBaseSelect: typeof import("../components/base/Select.vue")['default']
export const LazyBaseSkeleton: typeof import("../components/base/Skeleton.vue")['default']
export const LazyBaseTab: typeof import("../components/base/Tab.vue")['default']
export const LazyBaseTextarea: typeof import("../components/base/Textarea.vue")['default']
export const LazyBaseToast: typeof import("../components/base/Toast.vue")['default']
export const LazyBaseToastBar: typeof import("../components/base/ToastBar.vue")['default']
export const LazyBaseUploadAvatar: typeof import("../components/base/UploadAvatar.vue")['default']
export const LazyBaseUploadImage: typeof import("../components/base/UploadImage.vue")['default']
export const LazyCompose: typeof import("../components/compose/index.vue")['default']
export const LazyLayoutsAdminHeader: typeof import("../components/layouts/admin/Header.vue")['default']
export const LazyLayoutsAdminSidebar: typeof import("../components/layouts/admin/Sidebar.vue")['default']
export const LazyLayoutsAdmin: typeof import("../components/layouts/admin/index.vue")['default']
export const LazyLayoutsShopHeader: typeof import("../components/layouts/shop/Header.vue")['default']
export const LazyLayoutsShopSidebar: typeof import("../components/layouts/shop/Sidebar.vue")['default']
export const LazyLayoutsShop: typeof import("../components/layouts/shop/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
